language: python
notifications:
  email: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
- pip install -r requirements-dev.txt
- pip install .
script:
- pytest
- sentinelhub S2A_MSIL1C_20170414T003551_N0204_R016_T54HVH_20170414T003551
