language: python
notifications:
  email: false
python:
- "3.5"
- "3.6"
before_install:
- sudo add-apt-repository -y ppa:jonathonf/backports
- sudo apt-get -qq update
- sudo apt-get install -y libopenjp2-7
install:
- pip install -r requirements-dev.txt
- pip install .
script:
- pylint sentinelhub/*.py
- radon cc sentinelhub/*.py -a -nb
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pytest --cov ./tests/ --ignore tests\test_ogc.py --ignore tests\test_data_request.py ; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pytest --cov ./tests/; fi'
